# Generated by Django 4.1.7 on 2023-03-30 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha_lanzamiento'], 'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
